#!/usr/bin/env python3
"""Check final IEEE-style figure filenames and write LaTeX includegraphics names."""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FIGURES_DIR = ROOT / "Figures"

TARGET_STEMS = [
    "Fig1_system_model",
    "Fig2_system_process",
    "Fig3_surrogate_model_compare",
    "Fig4a_eiffel_training_reward_curve",
    "Fig4b_eiffel_training_rgb_constraint_costs",
    "Fig4c_eiffel_training_depth_constraint_costs",
    "Fig4d_eiffel_training_qrgb_curve",
    "Fig4e_eiffel_training_rdepth_curve",
    "Fig4f_eiffel_policy_entropy_curve",
    "Fig5a_quality_q_gt",
    "Fig5b_quality_q_app",
    "Fig5c_quality_q_geo",
    "Fig6a_metric_psnr",
    "Fig6b_metric_ssim",
    "Fig6c_metric_lpips",
    "Fig6d_metric_chamfer",
    "Fig6e_metric_fscore",
    "Fig6f_metric_completeness",
    "Fig7a_crpo_guided_ppo",
    "Fig7b_lagrangian_ppo",
    "Fig7c_ppo_penalty",
    "Fig7d_random_allocation",
    "Fig7e_depth_priority_allocation",
    "Fig7f_reference",
]


def main() -> None:
    FIGURES_DIR.mkdir(parents=True, exist_ok=True)
    missing = []
    existing = []
    for stem in TARGET_STEMS:
        for suffix in (".pdf", ".png"):
            path = FIGURES_DIR / f"{stem}{suffix}"
            if path.exists():
                existing.append(path.name)
            else:
                missing.append(path.name)

    include_lines = [
        "% Auto-generated by tools/check_final_figure_files.py",
        "% Use the PDF names below in the paper.",
        "",
    ]
    for stem in TARGET_STEMS:
        pdf = f"{stem}.pdf"
        if (FIGURES_DIR / pdf).exists():
            include_lines.append(fr"\includegraphics[width=\linewidth]{{Figures/{pdf}}}")
        else:
            include_lines.append(fr"% MISSING: Figures/{pdf}")
    (FIGURES_DIR / "includegraphics_filenames.tex").write_text("\n".join(include_lines) + "\n")

    report_lines = [
        "# Final Figure Filename Check",
        "",
        "## Existing files",
        *[f"- `{name}`" for name in existing],
        "",
        "## Missing files",
        *([f"- `{name}`" for name in missing] or ["None"]),
        "",
        "## LaTeX includegraphics file",
        "- `Figures/includegraphics_filenames.tex`",
    ]
    (FIGURES_DIR / "final_figure_file_check.md").write_text("\n".join(report_lines) + "\n")

    print(f"checked {len(TARGET_STEMS)} figure stems under {FIGURES_DIR.relative_to(ROOT)}")
    print(f"existing files: {len(existing)}")
    print(f"missing files: {len(missing)}")
    if missing:
        for name in missing:
            print(f"missing: {name}")


if __name__ == "__main__":
    main()
